name: Maven Dependency Updates

on:
  schedule:
    - cron: "00 11 * * 2"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    uses: informalin/actions/.github/workflows/maven-update.yml@main
    with:
      with-submodules: true
    secrets:
      PAT: ${{ secrets.SDQ_TOKEN }}
